### ISSUE TITLE
Attachments are not sent

### ISSUE THREAD

**Issue by daankets** [Cellarise/loopback-connector-sendgrid#1]
It seems like any attachments included in the message are NOT sent using this API.

**Comment by JohnMBarry** [comment]
Added support for option.files in v1.1.0 - see commit 64c22a1 . Note I haven't tested or documented this feature yet.

Pass an array of file configuration objects to options.files e.g.
options.files = {
  filename: 'secret.txt',
  content:  new Buffer('You will never know....')
}
See the [sendgrid](https://www.npmjs.com/package/sendgrid) api for more examples.
