### ISSUE TITLE
V3 API is denying requests, possibly due to malformed request object

### ISSUE THREAD

**Issue by oppodeldoc** [Cellarise/loopback-connector-sendgrid#10]
Hi @JohnMBarry and thanks for your work on this project!

When I upgraded to your latest version on NPM, it immediately stopped being able to send emails using the request format specified in the Readme doc. This might just be out of date docs but after combing through the code a bit I think maybe this version is broken for the V3 SendGrid API. I rolled back to 1.2.3 and it works again. 

A little bit of experimentation shows errors like this:
```
 {statusCode: 400,
  body: '{"errors":[{"message":"The content value must be a string at least one character in length.","field":"content.0.value","help":"http://sendgrid.com/docs/API_Reference/Web_API_v3/Mail/errors.html#message.content.value"}]}',
  headers:
   { server: 'nginx',
     date: 'Tue, 12 Jul 2016 23:47:49 GMT',
     'content-type': 'application/json',
     'content-length': '219',
     connection: 'close',
     'x-frame-options': 'DENY' } }
```
I was earlier getting the same types of errors on the "to" field as well and had to make some adjustments [here](https://github.com/Cellarise/loopback-connector-sendgrid/blob/master/lib/sendgrid.js#L98-L105) to keep "to" from being passed in as an array.

There are other issues, I just wanted to check and see if this is on your radar or if there's something I'm missing here. Happy to submit a PR later this week if I have time to work through it but don't want to do that if you're already on it.  Thanks again!

**Comment by JohnMBarry** [comment]
Hi @oppodeldoc, I have been distracted from this project for a few weeks. I'd be more than happy to receive a PR if you have time.
cheers JB
