### ISSUE TITLE
how to use unique_args in loopback connector? and what is tracking_settings in datasource.json?

### ISSUE THREAD

**Issue by pankajm** [Cellarise/loopback-connector-sendgrid#12]

**Comment by JohnMBarry** [comment]
Hi @pankajm please see pull request #26 . Re tracking_settings this is untested but supposed to provide functionality listed here: [](https://sendgrid.com/docs/API_Reference/Web_API_v3/Settings/tracking.html).
Apologies about late reply.
cheers John
