### ISSUE TITLE
Invalid type of To email (found)

### ISSUE THREAD

**Issue by nthiep** [Cellarise/loopback-connector-sendgrid#13]
body: '{"errors":[{"message":"Invalid type. Expected: string, given: array.","field":"personalizations.0.to.0.email","help":"http://sendgrid.com/docs/API_Reference/Web_API_v3/Mail/errors.html#message.personalizations.to"}]}',

i found this line:
//email to param
    if (R.is(String, options.to)) {
      sendgridMessage.to = options.to.split(',');
    }
it return to array

**Comment by saurabh73** [comment]
Facing same issue...

**Comment by jeisenlo** [comment]
+1 I have the same issue

**Comment by JohnMBarry** [comment]
Hi all, sorry for late response.  I don't have access to sendgrid at the moment which makes it almost impossible to properly test the new V3 api. Happy for anyone to try and sned pull requests if there are any other issues.
Please try version 2.0.4
