### ISSUE TITLE
sendGridLib.SendGrid is not a function

### ISSUE THREAD

**Issue by jeisenlo** [Cellarise/loopback-connector-sendgrid#14]
Using v2.0.4

TypeError: Cannot create data source "sendgrid": Cannot initialize connector "SendgridConnector": sendGridLib.SendGrid is not a function

I see the following code:

`if (settings.api_key){
this.sendgrid = sendGridLib.SendGrid(settings.api_key); //eslint-disable-line
 }`

I double checked that my Sendgrid API Key is correct and even created a new one and tried again with no luck. Any thoughts?

**Comment by dfromero** [comment]
same here just updated the package and got this, any quick fix meanwhile ?

**Comment by JohnMBarry** [comment]
Sorry I'm unable to test this package properly. I've made a change in 2.0.5 to instantiate sendgrid based on the v3 API. Please let me know if it works.
