### ISSUE TITLE
From address specification mismatch

### ISSUE THREAD

**Issue by daankets** [Cellarise/loopback-connector-sendgrid#2]
The NodeMailer API allows you to define a formatted from address like this:
```json
{
    "name":"Some Sender",
    "address":"someaddress@some.domain"
}
```

However, this implementation somehow replaced 'address' with 'email'. It should at least default to the `from.address` property.

**Comment by JohnMBarry** [comment]
Should be fixed in v1.1.0 - see commit 64c22a1
