### ISSUE TITLE
Remove non existing directories from package.json

### ISSUE THREAD

**Issue by rhansma** [Cellarise/loopback-connector-sendgrid#20]
On line https://github.com/Cellarise/loopback-connector-sendgrid/blob/master/package.json#L77 the directory bin is listed, the directory doesn't exists however. This causes the package manager YARN to crash.

Also see: https://github.com/yarnpkg/yarn/issues/739#issuecomment-254219494

Removing this directory should fix the issue.

**Comment by JohnMBarry** [comment]
See version 2.1.1
