### ISSUE TITLE
Update version of sendgrid

### ISSUE THREAD

**Issue by marsanla** [Cellarise/loopback-connector-sendgrid#30]
Please can you update the version of sendgrid to 6.1.4

Thanks

**Comment by zbarbuto** [comment]
Out of curiosity why was this closed?

Looks to me like sendgrid moved anyway when releasing 6.0:

https://www.npmjs.com/package/@sendgrid/mail

**Comment by zbarbuto** [comment]
Did find this which already uses 6.x:

https://github.com/VMois/loopback-sendgrid-connector
