### ISSUE TITLE
[Error: Bad username / password]

### ISSUE THREAD

**Issue by tratnayake** [Cellarise/loopback-connector-sendgrid#4]
Set-Up:
I have 1. Set up an entry in datasources.json 
```"sendgrid": {
        "connector": "loopback-connector-sendgrid",
        "api_user": "MYUSERNAMEHERE",
        "api_key": "MYKEYHERE"
    }```

2. I have set up an entry in my model-config.json:
``` "Email": {
          "dataSource": "sendgrid",
          "public": false
      }```

I do not know where to make the js configuration entry ( as mentioned in the readme) however I have tried testing it inside the loopback application's server.js.

I have done it the following way: (inside server.js)
```
var loopback = require('loopback');
var boot = require('loopback-boot');

var app = module.exports = loopback();

app.start = function() {

  var DataSource = require('loopback-datasource-juggler').DataSource;
  var dsSendGrid = new DataSource('loopback-connector-sendgrid', {
      "api_user": 'MYUSERNAMEHERE',
      "api_key": 'MYKEYHERE'
  });
  loopback.Email.attachTo(dsSendGrid);
  console.log("Sendgrid attached");

  loopback.Email.send({
      to: "test@to.com",
      from: "test@from.com",
      subject: "subject",
      text: "text message",
      html: "html <b>message</b>"
  },
  function(err, result) {
      if(err) {
          console.log(err);
          console.log('Upppss something crash');
          return;
      }
      console.log(result);
  });

  // start the web server
  return app.listen(function() {
    app.emit('started');
    var baseUrl = app.get('url').replace(/\/$/, '');
    console.log('Web server listening at: %s', baseUrl);
    if (app.get('loopback-component-explorer')) {
      var explorerPath = app.get('loopback-component-explorer').mountPath;
      console.log('Browse your REST API at %s%s', baseUrl, explorerPath);
    }
  });

};

// Bootstrap the application, configure models, datasources and middleware.
// Sub-apps like REST API are mounted via boot scripts.
boot(app, __dirname, function(err) {
  if (err) throw err;

  // start the server if `$ node server.js`
  if (require.main === module)
    app.start();
});

```

however an email never gets sent and I get the error:
```
[Error: Bad username / password]
Upppss something crash
```

I have confirmed that I am using my sendgrid username & a new/proper API key.

Any suggestions?

**Comment by JohnMBarry** [comment]
Could you try removing the api_user property e.g.
```
var dsSendGrid = new DataSource('loopback-connector-sendgrid', {
      "api_key": 'MYKEYHERE'
  });
```

**Comment by tratnayake** [comment]
This worked! Thank-you :)

**Comment by slonoed** [comment]
@JohnMBarry could you add this info for new users. (when api_token is used instead password – omit username)

**Comment by JohnMBarry** [comment]
Thanks will do
